services:
  - type: web
    name: aarogya-drishti
    env: python
    runtime: python-3.10   # Allows patch-level security updates
    buildCommand: "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT backend.app_deploy:app"
    envVars:
      - key: PORT
        value: 10000
